const suburbsByState = [
  {
    state: "Victoria",
    suburbs: [
      "Albert Park",
      "Altona North",
      "Balwyn",
      "Berwick",
      "Blackburn",
      "Brighton",
      "Carlton",
      "Caroline Springs",
      "Croydon",
      "Dandenong",
      "Docklands",
      "Doncaster",
      "East Melbourne",
      "Elwood",
      "Fitzroy",
      "Footscray",
      "Frankston",
      "Glen Waverley",
      "Hawthorn East",
      "Hoppers Crossing",
      "Kensington",
      "Langwarrin",
      "Lynbrook",
      "Melbourne (CBD)",
      "Mill Park",
      "Mount Eliza",
      "Noble Park",
      "North Melbourne",
      "Patterson Lakes",
      "Point Cook",
      "Port Melbourne",
      "Reservoir",
      "Richmond",
      "Rowville",
      "Southbank",
      "St Kilda",
      "Sunbury",
      "Templestowe",
      "Werribee",
      "West Melbourne",
      "Yarraville",
    ],
  },
  {
    state: "New South Wales",
    suburbs: [
      "Armidale",
      "Auburn",
      "Bankstown",
      "Blacktown",
      "Bondi",
      "Castle Hill",
      "Coffs Harbour",
      "Collaroy",
      "Cowra",
      "Dubbo",
      "Eastwood",
      "Homebush West",
      "Hurstville",
      "Ingleburn",
      "Kellyville",
      "Kincumber",
      "Kings Langley",
      "Liverpool",
      "Macquarie Fields",
      "Manly",
      "Matraville",
      "Meadowbank",
      "Merrylands",
      "Mount Druitt",
      "Mudgee",
      "Newtown",
      "North Narrabeen",
      "Paddington",
      "Parramatta",
      "Pemulwuy",
      "Port Macquarie",
      "Quakers Hill",
      "Queanbeyan",
      "Rouse Hill",
      "Seven Hills",
      "Surry Hills",
      "Sydney (CBD)",
      "Wentworthville",
    ],
  },
  {
    state: "Queensland",
    suburbs: [
      "Arundel",
      "Ashgrove",
      "Bracken Ridge",
      "Brighton",
      "Brisbane (CBD)",
      "Currumbin Waters",
      "Ferny Grove",
      "Fortitude Valley",
      "Hope Island",
      "Ipswich",
      "Manly",
      "Milton",
      "Moorooka",
      "New Farm",
      "Nundah",
      "Oxley",
      "Paddington",
      "Paradise Point",
      "Petrie",
      "Pimpama",
      "Port Douglas",
      "Redcliffe",
      "Sandgate",
      "Southport",
      "Springfield Lakes",
      "Stafford",
      "Surfers Paradise",
      "Toowong",
      "Toowoomba City",
      "West End",
      "Woodridge",
    ],
  },
  {
    state: "South Australia",
    suburbs: [
      "Aldinga Beach",
      "Blakeview",
      "Davoren Park",
      "Flagstaff Hill",
      "Glenelg",
      "Mawson Lakes",
      "McLaren Flat",
      "Mount Gambier",
      "Myrtle Bank",
      "North Adelaide",
      "North Haven",
      "Plympton Park",
      "Prospect",
      "Ridgehaven",
      "Royal Park",
      "Seaford Rise",
    ],
  },
  {
    state: "Western Australia",
    suburbs: [
      "Aubin Grove",
      "Dianella",
      "Doubleview",
      "Duncraig",
      "Langford",
      "Mindarie",
      "Northam",
      "Perth (CBD)",
      "Rivervale",
      "Secret Harbour",
      "Tapping",
      "Willetton",
      "Woodvale",
    ],
  },
  {
    state: "Tasmania",
    suburbs: [
      "Blackmans Bay",
      "Bridgewater",
      "George Town",
      "Glenorchy",
      "Hobart",
      "Launceston",
      "Longford",
      "Norwood",
      "Queenstown",
      "South Hobart",
    ],
  },
  {
    state: "Australian Capital Territory",
    suburbs: ["City", "Parkes", "Red Hill"],
  },
];

module.exports = suburbsByState;